name: LimonAntiCheat
version: 1.0.0
main: com.limonanarchy.anticheat.AntiCheatPlugin
api-version: '1.21'
author: LimonAnarchy
softdepend: [ViaVersion, ViaBackwards]
commands:
  ac:
    description: Anticheat admin commands
    permission: anticheat.admin
    usage: /ac <reload|violations|ban|unban>
    aliases: [anticheat]
  report:
    description: Пожаловаться на игрока
    permission: report.use
    usage: /report <ник> <причина>
  reports:
    description: Посмотреть список репортов
    permission: reports.view
    usage: /reports
  spec:
    description: Спектейтор-слежка за игроком
    permission: spec.use
    usage: /spec <ник|off>
  acprov:
    description: Вызвать игрока на проверку через AnyDesk (телепорт в камеру)
    permission: anticheat.admin
    usage: /acprov <ник|setroom> [off|target|reviewer]
permissions:
  anticheat.admin:
    default: op
  anticheat.bypass:
    default: false
  report.use:
    default: true
  reports.view:
    default: op
  spec.use:
    default: op
